name: deploy lektor
# TODO: run nightly
on:
  workflow_dispatch:
  push:
  schedule:
    # run every night at 2:59 am PST
    - cron:  '59 10 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    environment: action
    steps:
    - uses: actions/checkout@v3
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O content/contents.lr https://raw.githubusercontent.com/kleutzinger/kleutzinger.github.io/master/site-generator/generated/kevbot.xyz.contents.lr
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update contents.lr
        commit_options: '--no-verify'
        commit_user_name: GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <github-actions[bot]@users.noreply.github.com>
        file_pattern: content/contents.lr
    - run: |
        # run python
        # activate virtual environment
        python -m venv venv
        . venv/bin/activate
        python -m pip install -r requirements.txt
        python -m lektor build -O dist
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
