name: Nightly update from google sheet
# TODO: run nightly
on:
  workflow_dispatch:
  schedule:
    # run every night at 2:59 am PST
    - cron:  '59 10 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
        # activate virtual environment
        python -m venv venv
        . venv/bin/activate
        python -m pip install -r requirements.txt
        python3 site-generator/generate.py
        python3 site-generator/kevbot.xyz.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update site
        commit_options: '--no-verify'
        commit_user_name: GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <github-actions[bot]@users.noreply.github.com>
        file_pattern: index.html site-generator/generated/*
    - uses: gacts/purge-jsdelivr-cache@v1
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      with:
        url: |
          https://cdn.jsdelivr.net/gh/kleutzinger/kleutzinger.github.io/site-generator/generated/projects.json
          https://cdn.jsdelivr.net/gh/kleutzinger/kleutzinger.github.io/site-generator/kevbadge.js
